# Estágio 1: Instalar o Node.js e o npm
FROM node:latest

RUN touch /home/node/.bashrc | echo "PS1='\w\$ '" >> /home/node/.bashrc

RUN npm config set cache /home/node/app/.npm-cache --global

WORKDIR /app

RUN npm install -g @angular/cli@^16.1.5

CMD ["ng", "serve", "--host", "0.0.0.0"]
