###
POST http://localhost:8080/realms/storage-app-realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=whatsapp-api-client
&client_secret=C4o6aozEUR9mraJPWZQkB7kmUTwwidKh
&username=sistema@storage.app.br
&password=senha
&grant_type=password
&scope=openid